# Generated by Django 4.2.16 on 2024-10-15 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={
                'verbose_name': 'FilmWork',
                'verbose_name_plural': 'FilmWorks',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={
                'verbose_name': 'FilmWork genre',
                'verbose_name_plural': 'FilmWork genres',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={
                'verbose_name': 'Person FilmWork',
                'verbose_name_plural': 'Persons FilmWork',
            },
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='genrefilmwork',
            name='film_work',
        ),
        migrations.RemoveField(
            model_name='genrefilmwork',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personfilmwork',
            name='film_work',
        ),
        migrations.RemoveField(
            model_name='personfilmwork',
            name='person',
        ),
        migrations.AddField(
            model_name='genrefilmwork',
            name='film_work_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.filmwork',
                verbose_name='FilmWork',
            ),
        ),
        migrations.AddField(
            model_name='genrefilmwork',
            name='genre_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.genre',
                verbose_name='Genre',
            ),
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='film_work_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.filmwork',
                verbose_name='FilmWork',
            ),
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='person_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.person',
                verbose_name='Person',
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(
                blank=True, null=True, verbose_name='creation_date'
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='rating',
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(
                choices=[('movie', 'movie'), ('tv_show', 'tv_show')],
                default='movie',
                max_length=20,
                verbose_name='type',
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(blank=True, verbose_name='Role'),
        ),
    ]
